# Path to your oh-my-zsh installation.
export ZSH=/Users/tlemoine/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="lambda-mod"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git zsh-completions)

# User configuration

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# *****************
# Custom
# *****************
alias zshconfig="vim ~/.zshrc"
alias vimconfig="vim ~/.vimrc"
alias j6='export JAVA_HOME=$(/usr/libexec/java_home -v 1.6*)'
alias j7='export JAVA_HOME=$(/usr/libexec/java_home -v 1.7*)'
alias j8='export JAVA_HOME=$(/usr/libexec/java_home -v 1.8*)'

export EDITOR=vim
export PATH="$HOME/bin:$HOME/.rbenv/bin:$HOME/npm/bin:$PATH"

# Get a simple webserver. Thanks, Paul Irish!
function server() {
  local port="${1:-8000}"
  open "http://localhost:${port}/"
  python -m SimpleHTTPServer "${port}"
}

# Create a new directory and enter it
function md() {
  mkdir -p "$@" && cd "$@"
}


# find shorthand
function f() {
    find . -name "$1"
}

# code () { VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $* ;}
# eval "$(rbenv init -)"

# z
. /usr/local/etc/profile.d/z.sh

export NVM_DIR="$HOME/.nvm"
. "/usr/local/opt/nvm/nvm.sh"


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Minimal prompt
autoload -U promptinit; promptinit
prompt pure
